# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: dev
spec:
  selector:
    app: mydep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Or ClusterIP if accessed internally
