apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - image: nakaderahul94/login_page_project:1
        name: login-front-continer
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_HOST
            value: mysql-service # Name of your MySQL Kubernetes Service
          - name: MYSQL_USER
            value: your_mysql_username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials # Kubernetes Secret for MySQL password
                key: password
          - name: MYSQL_DATABASE
            value: your_database_name
